name: Build Android APK (Debug)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Instala SDK Android y acepta licencias
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # Instala Gradle 8.7 para AGP 8.5.x
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      # Compila el APK de debug (ajusta el módulo si no es :app)
      - name: Assemble Debug
        run: gradle :app:assembleDebug --no-daemon

      # Publica el APK como artefacto descargable
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MagisFreeInstaller-debug
          path: app/build/outputs/apk/debug/*.apk
